Project/OnlineLearningSystem/Models/ExaminationPaperTemplate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace OnlineLearningSystem.Models
{
    public class ExaminationPaperTemplate
    {
        [Key]
        public Int32 EPT_Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Int32 EPT_AutoId { get; set; }

        public Int32 ET_Id { get; set; }

        public Byte ET_Type { get; set; }

        [NotMapped]
        public String ET_Name { get; set; }

        [DisplayName("试卷模板状态")]
        public Byte EPT_PaperTemplateStatus { get; set; }

        [DisplayName("开始日期")]
        [DataType(DataType.DateTime)]
        public DateTime EPT_StartDate { get; set; }

        [DisplayName("开始时间")]
        [DataType(DataType.DateTime)]
        public DateTime EPT_StartTime { get; set; }

        [DisplayName("结束时间")]
        [DataType(DataType.DateTime)]
        public DateTime EPT_EndTime { get; set; }

        [DisplayName("时长")]
        public Int32 EPT_TimeSpan { get; set; }

        [DisplayName("试题模板")]
        public String EPT_Questions { get; set; }

        [DisplayName("备注")]
        [MaxLength(200, ErrorMessage="请输入小于200个字符的内容。")]
        public String EPT_Remark { get; set; }

        [DisplayName("添加时间")]
        [DataType(DataType.DateTime)]
        public DateTime EPT_AddTime { get; set; }

        [DisplayName("状态")]
        [Required(ErrorMessage = "请选择{0}")]
        public Byte EPT_Status { get; set; }

        [NotMapped]
        public String EP_Score { get; set; }

        [NotMapped]
        public Byte EP_PaperStatus { get; set; }
    }
}

Project/OnlineLearningSystem/Controllers/ExaminationPaperTemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using OnlineLearningSystem.Models;
using OnlineLearningSystem.Utilities;
//using Newtonsoft.Json;

namespace OnlineLearningSystem.Controllers
{
    public class ExaminationPaperTemplateController : OLSController
    {

        UExaminationPaperTemplate um = new UExaminationPaperTemplate();

        //
        // GET: /ExaminationPaperTemplate/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /ExaminationPaperTemplate/List

        [Description("试卷模板列表，管理后台")]
        public ActionResult List()
        {
            return View();
        }


        //
        // GET: /ExaminationPaperTemplate/ListStudent

        [Description("试卷模板列表，学员后台")]
        public ActionResult ListStudent()
        {
            return View();
        }

        //
        // POST: /ExaminationPaperTemplate/ListDataTablesAjax

        [Description("查询试卷模板，管理后台")]
        public JsonResult ListDataTablesAjax(Int32 etId)
        {

            DataTablesRequest dtRequest;
            DataTablesResponse dtResponse;

            dtRequest = GetDataTablesRequest();
            dtResponse = um.ListDataTablesAjax(dtRequest, etId);

            return Json(dtResponse, JsonRequestBehavior.DenyGet);
        }

        //
        // POST: /ExaminationPaperTemplate/ListDataTablesAjaxStudent

        /*[Description("查询试卷模板，学员后台")]
        public JsonResult ListDataTablesAjaxStudent(Byte type, Byte ptStatus)
        {

            Int32 uId;
            DataTablesRequest dtRequest;
            DataTablesResponse dtResponse;

            uId = ((User)Session["User"]).U_Id;

            dtRequest = GetDataTablesRequest();
            dtResponse = um.ListDataTablesAjax(dtRequest, uId, type, ptStatus);

            return Json(dtResponse, JsonRequestBehavior.DenyGet);
        }*/
        [Description("查询试卷模板，学员后台")]
        public JsonResult ListDataTablesAjaxStudent(Byte etType, Byte pageType)
        {

            Int32 uId;
            DataTablesRequest dtRequest;
            DataTablesResponse dtResponse;

            uId = ((User)Session["User"]).U_Id;

            dtRequest = GetDataTablesRequest();
            dtResponse = um.ListDataTablesAjaxStudent(dtRequest, uId, etType, pageType);

            return Json(dtResponse, JsonRequestBehavior.DenyGet);
        }

        //
        // GET: /ExaminationPaperTemplate/Paper

        [Description("进入考试")]
        public ActionResult Paper(Int32 id)
        {

            User u;
            ResponseJson resJson;

            u = (User)Session["User"];
            resJson = um.EnterExamination(id, u.U_Id);

            if (ResponseStatus.Success == resJson.status)
            {
                return RedirectToAction("Paper", "ExaminationPaper", new { epId = resJson.addition });
            }

            resJson.message = resJson.message.Replace("\\r\\n", "||r||n").Replace("\r\n", "|r|n");

            return Redirect("/Contents/html/prompt_redirect.htm?prompt=" + resJson.message + "&close=1");
        }

        //
        // GET: /ExaminationPaperTemplate/ListGrade

        [Description("改卷列表")]
        public ActionResult ListGrade()
        {
            return View();
        }

        //
        // GET: /ExaminationPaperTemplate/GetUsers

        [Description("获取改卷用户数据")]
        public JsonResult GetUsers(Int32 id)
        {
            return Json(um.GetUsers(id),JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ExaminationPaperTemplate/GetQuestions

        [Description("获取改卷试题数据")]
        public JsonResult GetQuestions(Int32 id, Int32 epId, Int32 uId)
        {
            return Json(um.GetQuestions(id, epId, uId), JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ExaminationPaperTemplate/GetQuestionsForUser

        [Description("获取用户试题数据")]
        public JsonResult GetQuestionsForUser(Int32 eptId, Int32 epId)
        {

            Int32 uId;
            User u;

            u = (User)Session["User"];
            uId = u.U_Id;

            return Json(um.GetQuestions(eptId, epId, uId), JsonRequestBehavior.AllowGet);
        }

        //
        // POST: /ExaminationPaperTemplate/Grade

        [Description("提交改卷数据")]
        [HttpPost]
        public JsonResult Grade(String gradeJson)
        {
            return Json(um.Grade(gradeJson));
        }

        //
        // GET: /ExaminationPaperTemplate/Create

        [Description("新建试卷模板")]
        [HttpGet]
        public ActionResult Create(Int32 etId)
        {

            ExaminationPaperTemplate m;

            m = um.GetNew(etId);

            return View(m);
        }

        //
        // POST: /ExaminationPaperTemplate/Create

        [Description("添加试卷模板")]
        [HttpPost]
        public ActionResult Create(ExaminationPaperTemplate m)
        {

            if (ModelState.IsValid)
            {

                if (um.Create(m))
                {
                    return Redirect("/Contents/html/parent_reload.htm");
                }
            }

            return View(m);
        }

        //
        // GET: /ExaminationPaperTemplate/Edit

        [Description("查看试卷模板")]
        [HttpGet]
        public ActionResult Edit(Int32 id)
        {

            ExaminationPaperTemplate m;

            m = um.Get(id);

            return View(m);
        }

        //
        // POST: /ExaminationPaperTemplate/Edit

        [Description("修改试卷模板")]
        [HttpPost]
        public ActionResult Edit(ExaminationPaperTemplate m)
        {

            if (ModelState.IsValid)
            {

                if (um.Edit(m))
                {
                    return Redirect("/Contents/html/parent_reload.htm");
                }
            }

            return View(m);
        }

        //
        // GET: /ExaminationPaperTemplate/Recycle

        [Description("回收试卷模板")]
        public JsonResult Recycle(Int32 id)
        {

            ResponseJson resJson;

            resJson = um.Recycle(id);

            return Json(resJson, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ExaminationPaperTemplate/Resume

        [Description("恢复试卷模板")]
        public JsonResult Resume(Int32 id)
        {

            ResponseJson resJson;

            resJson = um.Resume(id);

            return Json(resJson, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ExaminationPaperTemplate/Delete

        [Description("删除试卷模板")]
        public JsonResult Delete(Int32 id)
        {

            ResponseJson resJson;

            resJson = um.Delete(id);

            return Json(resJson, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ExaminationPaperTemplate/Terminate

        [Description("终止考试")]
        public JsonResult Terminate(Int32 id)
        {

            ResponseJson resJson;

            resJson = um.Terminate(id);

            return Json(resJson, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ExaminationPaperTemplate/PaperView

        [Description("查看试卷")]
        public ActionResult PaperView()
        {
            return View();
        }

        //
        // GET: /ExaminationPaperTemplate/PaperGrade

        [Description("评改试卷")]
        public ActionResult PaperGrade()
        {
            return View();
        }

        //
        // GET: /ExaminationPaperTemplate/EnterExercise

        [Description("进入练习")]
        public ActionResult EnterExercise(Int32 etId)
        {

            User u = (User)Session["User"];
            ResponseJson resJson = um.EnterExercise(etId, u.U_Id);

            if (ResponseStatus.Success == resJson.status)
            {
                return RedirectToAction("Paper", "ExaminationPaper", new { epId = resJson.data });
            }

            resJson.message = resJson.message.Replace("\\r\\n", "||r||n").Replace("\r\n", "|r|n");

            return Redirect("/Contents/html/prompt_redirect.htm?prompt=" + resJson.message + "&close=1");
        }

    }
}

Project/OnlineLearningSystem/Views/ExaminationPaperTemplate/Create.cshtml
@model OnlineLearningSystem.Models.ExaminationPaperTemplate
@{
    ViewBag.Title = "添加试卷模板";
    Layout = "~/Views/Shared/_PageEdit.cshtml";
}
<div class="pd-20">
    @using (Html.BeginForm("Create", "ExaminationPaperTemplate", FormMethod.Post, new { name = "create", @class = "form form-horizontal" }))
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(m => m.EPT_Id)
        @Html.HiddenFor(m => m.ET_Id)
        @Html.HiddenFor(m => m.ET_Type)
        @Html.HiddenFor(m => m.EPT_PaperTemplateStatus)
        @Html.HiddenFor(m => m.EPT_StartTime)
        @Html.HiddenFor(m => m.EPT_EndTime)
        @Html.HiddenFor(m => m.EPT_TimeSpan)
        @Html.HiddenFor(m => m.EPT_AutoId)
        @Html.HiddenFor(m => m.EPT_AddTime)
        <div class="row cl">
            <label class="form-label col-2">
                @Html.LabelFor(m => m.EPT_Status)
            </label>
            <div class="formControls col-2">
                <span class="select-box">
                    @Html.EditorFor(m => m.EPT_Status, "Status")
                </span>
                @Html.ValidationMessageFor(m => m.EPT_Status)
            </div>
        </div>
        <!--div class="row cl">
            <label class="form-label col-2">
                @Html.LabelFor(m => m.EPT_StartTime)
            </label>
            <div class="formControls col-2">
                @Html.TextBoxFor(m => m.EPT_StartTime, new { @class = "input-text" })
                @Html.ValidationMessageFor(m => m.EPT_StartTime)
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-2">
                @Html.LabelFor(m => m.EPT_TimeSpan)
            </label>
            <div class="formControls col-2">
                @Html.TextBoxFor(m => m.EPT_TimeSpan, new { @class = "input-text" })
                @Html.ValidationMessageFor(m => m.EPT_TimeSpan)
            </div>
        </div-->
        <div class="row cl">
            <label class="form-label col-2">
                @Html.LabelFor(m => m.EPT_Questions)
            </label>
            <div class="formControls col-10">
                <table class="table table-border table-bordered table-bg table-hover table-sort question-table"
                    value-selector="#EPT_Questions">
                    <thead>
                        <tr>
                            <th class="text-c">
                                <input type="checkbox" name="" value="all" />
                            </th>
                            <th>
                                ID
                            </th>
                            <th>
                                题型
                            </th>
                            <th>
                                分类
                            </th>
                            <th>
                                添加时间
                            </th>
                            <th>
                                试题
                            </th>
                            <th>
                                难度系数
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                @Html.HiddenFor(m => m.EPT_Questions)
            </div>
        </div>
        <div class="row cl">
            <div class="col-10 col-offset-2">
                <input class="btn btn-primary radius" type="submit" value="&nbsp;&nbsp;保存&nbsp;&nbsp;" />
                <button onclick="layer_close();" class="btn btn-default radius" type="button">
                    &nbsp;&nbsp;取消&nbsp;&nbsp;</button>
            </div>
        </div>
    }
</div>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/js.datetime.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/datatables/1.10.9/jquery.dataTables.min.js")"></script>
<script type="text/javascript" src="@Url.Content("/Contents/js/ExaminationPaperTemplate/Edit.js")"></script>
<script type="text/javascript" src="@Url.Content("/Contents/js/Question/ListSelect.js")"></script>

Project/OnlineLearningSystem/Views/ExaminationPaperTemplate/Edit.cshtml
@model OnlineLearningSystem.Models.ExaminationPaperTemplate
@{
    ViewBag.Title = "添加试卷模板";
    Layout = "~/Views/Shared/_PageEdit.cshtml";
}
<div class="pd-20">
    @using (Html.BeginForm("Edit", "ExaminationPaperTemplate", FormMethod.Post, new { name = "create", @class = "form form-horizontal" }))
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(m => m.EPT_Id)
        @Html.HiddenFor(m => m.ET_Id)
        @Html.HiddenFor(m => m.ET_Type)
        @Html.HiddenFor(m => m.EPT_PaperTemplateStatus)
        @Html.HiddenFor(m => m.EPT_StartTime)
        @Html.HiddenFor(m => m.EPT_EndTime)
        @Html.HiddenFor(m => m.EPT_TimeSpan)
        @Html.HiddenFor(m => m.EPT_AutoId)
        @Html.HiddenFor(m => m.EPT_AddTime)
        <div class="row cl">
            <label class="form-label col-2">
                @Html.LabelFor(m => m.EPT_Status)
            </label>
            <div class="formControls col-2">
                <span class="select-box">
                    @Html.EditorFor(m => m.EPT_Status, "Status")
                </span>
                @Html.ValidationMessageFor(m => m.EPT_Status)
            </div>
        </div>
        <!--div class="row cl">
            <label class="form-label col-2">
                @Html.LabelFor(m => m.EPT_StartTime)
            </label>
            <div class="formControls col-2">
                @Html.TextBoxFor(m => m.EPT_StartTime, new { @class = "input-text" })
                @Html.ValidationMessageFor(m => m.EPT_StartTime)
            </div>
        </div>
        <div class="row cl">
            <label class="form-label col-2">
                @Html.LabelFor(m => m.EPT_TimeSpan)
            </label>
            <div class="formControls col-2">
                @Html.TextBoxFor(m => m.EPT_TimeSpan, new { @class = "input-text" })
                @Html.ValidationMessageFor(m => m.EPT_TimeSpan)
            </div>
        </div-->
        <div class="row cl">
            <label class="form-label col-2">
                @Html.LabelFor(m => m.EPT_Questions)
            </label>
            <div class="formControls col-10">
                <table class="table table-border table-bordered table-bg table-hover table-sort question-table"
                    value-selector="#EPT_Questions">
                    <thead>
                        <tr>
                            <th class="text-c">
                                <input type="checkbox" name="" value="all" />
                            </th>
                            <th>
                                ID
                            </th>
                            <th>
                                题型
                            </th>
                            <th>
                                分类
                            </th>
                            <th>
                                添加时间
                            </th>
                            <th>
                                试题
                            </th>
                            <th>
                                难度系数
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                @Html.HiddenFor(m => m.EPT_Questions)
            </div>
        </div>
        <div class="row cl">
            <div class="col-10 col-offset-2">
                <input class="btn btn-primary radius" type="submit" value="&nbsp;&nbsp;保存&nbsp;&nbsp;" />
                <button onclick="layer_close();" class="btn btn-default radius" type="button">
                    &nbsp;&nbsp;取消&nbsp;&nbsp;</button>
            </div>
        </div>
    }
</div>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/js.datetime.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/datatables/1.10.9/jquery.dataTables.min.js")"></script>
<script type="text/javascript" src="@Url.Content("/Contents/js/ExaminationPaperTemplate/Edit.js")"></script>
<script type="text/javascript" src="@Url.Content("/Contents/js/Question/ListSelect.js")"></script>

Project/OnlineLearningSystem/Views/ExaminationPaperTemplate/List.cshtml
@{
    ViewBag.Title = "试卷模板";
    Layout = "~/Views/Shared/_Page.cshtml";
}
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 系统 <span class="c-gray en">&gt;</span> 试卷模板 <a class="btn btn-success radius r mr-20" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="pd-20">
    <div class="cl pd-5 bg-1 bk-gray">
        <!--span class="l">
            <a id="CreateBtn" class="btn btn-primary radius" href="javascript:void(0);">
               <i class="Hui-iconfont">&#xe600;</i> 添加模板 
            </a>
        </span-->
        <span class="l">
            <a id="GotoTaskListBtn" class="btn btn-success radius" href="javascript:void(0);">
               <i class="Hui-iconfont">&#xe66b;</i> 返回 
            </a>
        </span>
    </div>
    <div class="mt-20">
        <table class="table table-border table-bordered table-bg table-hover table-sort">
            <thead>
                <tr>
                    
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="cl"></div>
</div>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/js.datetime.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/My97DatePicker/WdatePicker.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/datatables/1.10.9/jquery.dataTables.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Contents/js/ExaminationPaperTemplate/List.js")"></script>

Project/OnlineLearningSystem/Views/ExaminationPaperTemplate/ListGrade.cshtml
@{
    ViewBag.Title = "试卷评分";
    Layout = "~/Views/Shared/_PageEdit.cshtml";
}
<div id="ExaminationPaperGradeContainer">
    <div id="UserList">
        <ul class="Huifold">
        </ul>
    </div>
    <div id="PaperContainer" class="ml-200">
    </div>
</div>
<script type="text/javascript" src="@Url.Content("/Contents/lib/jquery-tmpl/jquery.tmpl.min.js")"></script>
<script type="text/javascript" src="@Url.Content("/Contents/lib/jquery.timers-1.2.js")"></script>
<script type="text/javascript" src="@Url.Content("/Contents/js/OLS/PaperGrade.js")"></script>
<script type="text/javascript" src="@Url.Content("/Contents/js/ExaminationPaperTemplate/ListGrade.js")"></script>
<script id="UserItemTmpl" type="text/x-jquery-tmpl">
    <li id="Item_${U_Id}" class="item" data-user-id="${U_Id}" data-paper-id="${EP_Id}">
        <h4>${U_Name}<span class="score">${EP_Score}</span></h4>
    </li>
</script>
<script id="PaperTmpl" type="text/x-jquery-tmpl">
    <div id="Paper_${epId}" data-paper-id="${epId}" data-user-id="${uId}">
        {{tmpl(types) '#TypeTmpl'}}
        <div class="button-container">
            <button id="PrevPaper" class="btn btn-primary radius prev-paper mr-10" type="button">上一张</button>
            <button id="NextPaper" class="btn btn-primary radius next-paper mr-30" type="button">下一张</button>
            <button id="Grade" class="btn btn-primary radius next-paper mr-30" type="button">提交评分</button>
            <button id="GradeFinish" class="btn btn-primary radius f-r grade-finish mr-20" type="button">结束评分</button>
        </div>
    </div>
</script>
<script id="TypeTmpl" type="text/x-jquery-tmpl">
    <div class="question-container">
        <div class="type-name col-12">${type}</div>
        {{tmpl(questions) '#QuestionTmpl'}}
        <div class="cl"></div>
    </div>
</script>
<script id="QuestionTmpl" type="text/x-jquery-tmpl">
    <div class="col-12 cl question" data-eptq-id="${EPTQ_Id}">
        <div class="col-12 cl question-item question-content">
            <div class="col-12"><span class="tip">题</span>{{html EPTQ_Content}}</div>
        </div>
        <div class="col-12 cl question-item question-answer">
            <div class="col-12">
                <span class="tip">答</span>
                {{if EPTQ_Type == '单选题'}}
                    {{each(i, oa) EPTQ_OptionalAnswer}}
                    <span class="mr-10"><input type="radio" name="question_radios_${EPTQ_Id}" value="${oa.key}" class="mr-5" disabled />${oa.key}.${oa.text}</span>
                    {{/each}}
                {{else EPTQ_Type == '多选题'}}
                    {{each(i, oa) EPTQ_OptionalAnswer}}
                    <span class="mr-10"><input type="checkbox" name="question_checkboxs_${EPTQ_Id}" value="${oa.key}" class="mr-5" disabled />${oa.key}.${oa.text}</span>
                    {{/each}}
                {{else EPTQ_Type == '判断题'}}
                <span class="mr-10"><input type="radio" name="question_radios_${EPTQ_Id}" value="√" class="mr-5" disabled />√</span>
                <span class="mr-10"><input type="radio" name="question_radios_${EPTQ_Id}" value="×" class="mr-5" disabled />×</span>
                {{else EPTQ_Type == '公文改错题' || EPTQ_Type == '计算题' || EPTQ_Type == '案例分析题' || EPTQ_Type == '问答题'}}
                <br />
                <textarea name="question_textarea_${EPTQ_Id}" class="textarea disabled" cols="20" rows="2"></textarea>
                {{/if}}
            </div>
        </div>
        <div class="col-12 cl question-item question-grade">
            <div class="col-12">
                <span class="tip">标</span>
                <span data-id="ModelAnswerContainer_${EPTQ_Id}" class="fz-18"></span>
                {{if EPTQ_Type == '单选题'}}
                    {{each(i, oa) EPTQ_OptionalAnswer}}
                    <span class="mr-10 hide"><input type="radio" name="question_radios_${EPTQ_Id}_model_answer" value="${oa.key}" class="mr-5" disabled />${oa.key}.${oa.text}</span>
                    {{/each}}
                {{else EPTQ_Type == '多选题'}}
                    {{each(i, oa) EPTQ_OptionalAnswer}}
                    <span class="mr-10 hide"><input type="checkbox" name="question_checkboxs_${EPTQ_Id}_model_answer" value="${oa.key}" class="mr-5" disabled />${oa.key}.${oa.text}</span>
                    {{/each}}
                {{else EPTQ_Type == '判断题'}}
                <span class="mr-10 hide"><input type="radio" name="question_radios_${EPTQ_Id}_model_answer" value="√" class="mr-5" disabled />√</span>
                <span class="mr-10 hide"><input type="radio" name="question_radios_${EPTQ_Id}_model_answer" value="×" class="mr-5" disabled />×</span>
                {{else EPTQ_Type == '公文改错题' || EPTQ_Type == '计算题' || EPTQ_Type == '案例分析题' || EPTQ_Type == '问答题'}}
                <br />
                <textarea name="question_textarea_${EPTQ_Id}_model_answer" class="textarea disabled" cols="20" rows="2"></textarea>
                {{/if}}
            </div>
        </div>
        <div class="col-12 cl question-item question-grade">
            <div class="col-12">
                <span class="tip">评</span>
                <span data-id="question_radios_${EPTQ_Id}_grade_0" data-name="question_radios_${EPTQ_Id}_grade" data-value="0" class="grade unset fz-28 mr-10"><a href="javascript:void()" title="未评"><i class="Hui-iconfont">&#xe608;</i></a></span>
                <span data-id="question_radios_${EPTQ_Id}_grade_1" data-name="question_radios_${EPTQ_Id}_grade" data-value="1" class="grade exactness fz-28 mr-10"><a href="javascript:void()" title="正确"><i class="Hui-iconfont">&#xe676;</i></a></span>
                <span data-id="question_radios_${EPTQ_Id}_grade_2" data-name="question_radios_${EPTQ_Id}_grade" data-value="2" class="grade wrong fz-28 mr-10"><a href="javascript:void()" title="错误"><i class="Hui-iconfont">&#xe6dd;</i></a></span>
                <span class="mr-10 hide">
                    <label for="question_radios_${EPTQ_Id}_grade_0">
                        <input type="radio" id="question_radios_${EPTQ_Id}_grade_0" name="question_radios_${EPTQ_Id}_grade" value="0" class="mr-5" />未评
                    </label>
                </span>
                <span class="mr-10 hide">
                    <label for="question_radios_${EPTQ_Id}_grade_1">
                        <input type="radio" id="question_radios_${EPTQ_Id}_grade_1" name="question_radios_${EPTQ_Id}_grade" value="1" class="mr-5" />正确
                    </label>
                </span>
                <span class="mr-10 hide">
                    <label for="question_radios_${EPTQ_Id}_grade_2">
                        <input type="radio" id="question_radios_${EPTQ_Id}_grade_2" name="question_radios_${EPTQ_Id}_grade" value="2" class="mr-5" />错误
                    </label>
                </span>
            </div>
        </div>
        <div class="cl"></div>
    </div>
</script>

Project/OnlineLearningSystem/Views/ExaminationPaperTemplate/ListStudent.cshtml
@{
    ViewBag.Title = "试卷模板";
    Layout = "~/Views/Shared/_Page.cshtml";
}
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 系统 <span class="c-gray en">&gt;</span> 试卷 <a class="btn btn-success radius r mr-20" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="pd-20">
    <div class="mt-20">
        <table class="table table-border table-bordered table-bg table-hover table-sort">
            <thead>
                <tr>
                    
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="cl"></div>
</div>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/js.datetime.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/My97DatePicker/WdatePicker.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Contents/lib/datatables/1.10.9/jquery.dataTables.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Contents/js/ExaminationPaperTemplate/ListStudent.js")"></script>